ARG DOCKER_BASE
FROM $DOCKER_BASE

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get --no-install-recommends install -yq git cmake build-essential \
  libgl1-mesa-dev libsdl2-dev \
  libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libboost-all-dev \
  libdirectfb-dev libst-dev mesa-utils xvfb x11vnc \
  python3-pip

RUN python3 -m pip install --upgrade pip setuptools==65.5.0 wheel==0.38.0
RUN python3 -m pip install psutil six

COPY . /gfootball
RUN cd /gfootball && python3 -m pip install .
RUN pip3 install tensorflow==1.13.2
RUN pip3 install "git+https://github.com/openai/baselines.git@tf2#egg=baselines"
RUN pip3 install numpy==1.23.1 dm-sonnet==1.36
WORKDIR '/gfootball'
